
import "./globals.css";
import { vazir } from "../../public/font/vazir";
import { Layout } from "@/components/layout/Layout";
// import { Theme } from "@radix-ui/themes";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" className={vazir.variable} dir="rtl">

      <body className="font-[var(--font-vazir)]" >
        <Layout>{children}</Layout>
      </body>

    </html>
  );
}
